name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # 手動実行を可能にする

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and export static files
        run: npm run build
        env:
          GITHUB_ACTIONS: true
          NODE_ENV: production

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      - name: Check build output
        run: |
          echo "Checking build output directory..."
          ls -la ./out/
          echo "Checking for index.html..."
          if [ -f "./out/index.html" ]; then
            echo "✅ index.html found"
          else
            echo "❌ index.html not found"
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
